name: flutter_starter_app
version: 1.0.0+1
description: Flutter starter app providing sign-up, sign-in and sign-out functionnalities.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/flutter_Starter_App
issue_tracker: https://github.com/cbonello/flutter_Starter_App/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.17.0

dependencies:
  email_validator: ^1.0.0
  firebase_analytics: ^5.0.0
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.0
  flutter:
    sdk: flutter
  flutter_auth_buttons: ^0.10.0
  flutter_bloc: ^5.0.0
  flutter_focus_watcher: ^0.0.1
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^1.1.0
  freezed_annotation: ^0.11.0
  google_sign_in: ^4.5.0
  intl: ^0.16.0
  password_strength: ^0.1.0
  rxdart: ^0.24.0
  shared_preferences: '>=0.5.7+3 <2.0.0'

dev_dependencies:
  bloc_test: ^6.0.0
  build_runner: ^1.10.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^0.11.0
  intl_translation: ^0.17.0
  lint: ^1.2.0
  test: any
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
